---
# Routers, Mgmt Spines?
routers:
  ROUTER01:
    rack: RackDC1_P1_R1
    adapters:
      - endpoint_ports: [ Mgmt_Eth0, Mgmt_Eth1 ]
        switch_ports: [ Ethernet21, Ethernet21 ]
        switches: [ DC1-POD1-LEAF1A, DC1-POD1-LEAF1B ]
        profile: TENANT_A
